# Generated by Django 5.0.4 on 2024-08-10 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='care',
            name='created_at',
        ),
        migrations.AddField(
            model_name='care',
            name='care_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
