# Generated by Django 5.0.4 on 2024-08-10 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_care_created_at_care_care_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='care_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
