# Generated by Django 5.0.4 on 2024-08-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_diet_date_remove_exercise_date_petdiet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.AddField(
            model_name='sensor',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pet'),
            preserve_default=False,
        ),
    ]
